// Tipos de clientes relacionados con las industrias
export const clientTypes: Record<number, string[]> = {
    1: ["Programador", "Ingeniero de Software", "Diseñador UX/UI"],
    2: ["Médico", "Enfermero", "Especialista en Salud Mental"],
    3: ["Ingeniero Automotriz", "Mecánico de Automóviles", "Diseñador de Vehículos"],
    4: ["Chef", "Panadero", "Barista"],
    5: ["Ingeniero en Energías Renovables", "Técnico en Instalaciones Eléctricas"],
    6: ["Profesor", "Tutor", "Pedagogo"],
    7: ["Diseñador de Moda", "Estilista", "Modelo"],
    8: ["Guía Turístico", "Hotelero", "Agente de Viajes"],
    9: ["Actor", "Músico", "Productor de Cine"],
    10: ["Arquitecto", "Ingeniero Civil", "Topógrafo"],
    11: ["Banquero", "Analista Financiero", "Contador"],
    12: ["Agente de Bienes Raíces", "Arquitecto de Interiores", "Corredor de Propiedades"],
    13: ["Periodista", "Editor", "Presentador de Noticias"],
    14: ["Chofer", "Piloto", "Mecánico de Aviones"],
    15: ["Agricultor", "Agrónomo", "Técnico en Ganadería"],
    16: ["Controlador de inventario", "Inspector de calidad", "Operador de maquinaria"],
    17: ["Ingeniero en Telecomunicaciones", "Técnico en Redes", "Desarrollador de Software Telecom"],
    18: ["Abogado", "Consultor Legal", "Notario"],
    19: ["Ecologista", "Ingeniero Ambiental", "Reciclador"],
    20: ["Artista", "Curador de Arte", "Gestor Cultural"],
  };