export enum PATH {
  HOME = '',
  HOMEOPPORTUNITY = 'homeOpportunity',
  LOGIN = 'login',
  USERS = 'users',
  CREATEUSER = 'createUser',
  CREATEBUSINESS = 'createBusiness',
  EDITBUSINESS = 'editBusiness/:id',
  ALLBUSINESS = 'allBusiness',
  DETAILBUSINESS= 'detailBusiness/:id',
  MATCHESBYUSER = 'matchesByUser',
  USERBYID = 'userById',
  ALLUSERS = 'allUsers',
  EDITUSER = 'editUser',
  NOTIFICATIONS = 'notifications',
}
